##################### Metrics ##################################

# 自動生成ファイルを除く
AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*
    - db/migrate/*

# 日本語コメント許可
Style/AsciiComments:
  Enabled: false

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 160

# it_word/quizアクション
Metrics/AbcSize:
  Max: 24

# it_word/quizアクション
Metrics/MethodLength:
  Max: 23